name: django-lint

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  django-lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Preparar Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'    # Ajusta la versión si tu proyecto necesita otra

      # 3. Instalar dependencias mínimas para linting
      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          pip install ruff           # o flake8/black/isort si prefieres

      # 4. Ejecutar el linter en la carpeta Back
      - name: Run linter
        run: |
          ruff check --fix Back            # usa 'ruff check --fix Back' si quieres autocorrección

      # 5. (Opcional) Commit automático si el linter corrige archivos
      - name: Commit and push changes if Ruff fixed files
        if: ${{ github.event_name == 'pull_request' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Django Linting (Ruff)
          branch: master
          skip_fetch: true
