# .github/workflows/lint.yml
name: Lint Python Code

on:
  push:
    branches: [ master ]  # Se ejecuta solo en push a master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Puedes ajustar la versión según tu proyecto

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8 linter
      run: flake8 Back/inventario